services:
  # PostgreSQL база данных
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dev" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
  # Liquibase для миграций БД
  liquibase:
    image: liquibase/liquibase:4.20
    container_name: liquibase
    volumes:
      - ./db:/liquibase/changelog
      - ./liquibase.properties:/liquibase/liquibase.properties
    environment:
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://postgres:5432/dev
      - LIQUIBASE_COMMAND_USERNAME=postgres
      - LIQUIBASE_COMMAND_PASSWORD=postgres
      - LIQUIBASE_COMMAND_CHANGELOG_FILE=changelog/db.changelog-master.xml
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    command: [ "update" ]
    restart: "no"
    profiles:
      - migration
  # pgAdmin для управления БД
  pgweb:
    image: sosedoff/pgweb:latest
    container_name: pgweb
    ports:
      - "8081:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://postgres:postgres@postgres:5432/dev?sslmode=disable
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - postgres

  # NestJS приложение
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=dev
      - DB_SCHEMA=store
      - JWT_SECRET=your-jwt-secret-key
    ports:
      - "3000:3000"
    volumes:
      - uploads_data:/app/uploads  # Том для хранения загруженных изображений
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:
  uploads_data:  # Новый том для изображений

networks:
  app-network:
    driver: bridge
